/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_calculator_free: (a: number, b: number) => void;
export const __wbg_wasmjob_free: (a: number, b: number) => void;
export const calculator_active_op: (a: number) => [number, number];
export const calculator_display: (a: number) => [number, number];
export const calculator_full_result: (a: number) => [number, number];
export const calculator_has_big_result: (a: number) => number;
export const calculator_has_entry: (a: number) => number;
export const calculator_has_memory: (a: number) => number;
export const calculator_is_deg: (a: number) => number;
export const calculator_is_error: (a: number) => number;
export const calculator_is_second: (a: number) => number;
export const calculator_new: () => number;
export const calculator_press: (a: number, b: number, c: number) => void;
export const calculator_set_big_result: (a: number, b: number, c: number, d: number, e: number) => void;
export const calculator_take_long_job: (a: number) => [number, number];
export const calculator_tape: (a: number) => [number, number];
export const wasmjob_checkpoint: (a: number) => [number, number];
export const wasmjob_fromSpec: (a: number, b: number) => number;
export const wasmjob_isDone: (a: number) => number;
export const wasmjob_key: (a: number) => [number, number];
export const wasmjob_label: (a: number) => [number, number];
export const wasmjob_newFactorial: (a: number) => number;
export const wasmjob_newPow: (a: number, b: number) => number;
export const wasmjob_progress: (a: number) => number;
export const wasmjob_restore: (a: number, b: number) => number;
export const wasmjob_step: (a: number) => number;
export const wasmjob_toDecimal: (a: number) => [number, number];
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_start: () => void;
